
### fetch all notes
GET http://localhost:10000/api/notes/

### fetch note by id
GET http://localhost:10000/api/notes/1

### delete note by id
DELETE http://localhost:10000/api/notes/6915e7bc380abb48527e3efa

### update note by id
PUT http://localhost:10000/api/notes/691b114ef3ecf5de15e75519
Content-Type: application/json

{
    "content": "",
    "important": true
}

### create a new note
POST http://localhost:10000/api/notes
Content-Type: application/json

{
    "content": "lol",
    "important": false
}