
### fetch all notes
GET http://localhost:10000/api/notes/

### fetch note by id
GET http://localhost:10000/api/notes/692ea2ea4869cc3ecf2f8d43

### delete note by id
DELETE http://localhost:10000/api/notes/6915e7bc380abb48527e3efa

### update note by id
PUT http://localhost:10000/api/notes/691b114ef3ecf5de15e75519
Content-Type: application/json

{
    "content": "",
    "important": true
}

### create a new note
POST http://localhost:10000/api/notes
Content-Type: application/json

{
    "content": "this is second note",
    "important": false,
    "userId": "692dab78c24b87232f405763"

}

### post a new user
POST http://localhost:10000/api/users
Content-Type: application/json

{
    "username": "RZ0005",
    "name": "Rakib Zaman",
    "password": "rakib123@"
}

### fetch all users
GET http://localhost:10000/api/users