
### fetch all notes
GET http://localhost:3001/api/notes/

### fetch note by id
GET http://localhost:3001/api/notes/1

### delete note by id
DELETE http://localhost:3001/api/notes/2

### update note by id
PUT http://localhost:3001/api/notes/1

### create a new note
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Hello Rakib",
    "important": true
}